### ISSUE TITLE
clash.txt 文件中有乱码

### ISSUE THREAD

**Issue by lkxed** [MambaOutZY/FreeVmessSUB#1]
RT，可否修复一下？

![image](https://user-images.githubusercontent.com/39257389/126338009-b3147881-a3b2-4eda-8070-5921f942be2e.png)

**Comment by MambaOutZY** [comment]
周末我看看改改

**Comment by lkxed** [comment]
> 周末我看看改改

刚刚更新了下发现没有乱码了，谢谢！

**Comment by MambaOutZY** [comment]
已经做了更改。
